# Generated by Django 3.0.14 on 2022-03-08 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='beinexbooks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Bookname', models.CharField(max_length=240)),
                ('Author', models.CharField(max_length=240)),
                ('Description', models.CharField(max_length=240)),
            ],
        ),
        migrations.CreateModel(
            name='beinexusers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=240)),
                ('Username', models.CharField(max_length=240)),
                ('Password', models.CharField(max_length=240)),
                ('designation', models.CharField(max_length=240)),
            ],
        ),
    ]
