# Generated by Django 3.0.14 on 2022-03-08 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book_api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='beinexusers',
            old_name='designation',
            new_name='Designation',
        ),
    ]
