# Generated by Django 3.0.14 on 2022-03-08 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_api', '0002_auto_20220308_1327'),
    ]

    operations = [
        migrations.AddField(
            model_name='beinexbooks',
            name='Timestamp',
            field=models.CharField(default='0', max_length=240),
        ),
    ]
